version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_REACT_APP_USER_SERVICE_URL=http://localhost:5000/api/users
      - VITE_TASK_SERVICE_URL=http://localhost:5001
    depends_on:
      - user-service
      - task-service

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
