apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user
  template:
    metadata:
      labels:
        app: mongo-user
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo1-storage
              mountPath: /data/db
      volumes:
        - name: mongo1-storage
          persistentVolumeClaim:
            claimName: mongo1-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user-service
spec:
  selector:
    app: mongo-user
  ports:
    - port: 27017
      targetPort: 27017
